### PR TITLE
Corrections to code envs/ contribution guide/ local browsing

### PR DESCRIPTION
**Pull request by pireddag**
Now the incomplete file should be off (I will have questions on that when it is closer to be ready)

### CODE REVIEW

**Comment by pireddag** [comment]
Now I am working in the "work" branch and placing pull requests from "main". Sees sensible to me.

**Review by mgubi — APPROVED** [review]

**Comment by pireddag** [comment]
I have prepared a document on embedding TikZ figures (with the fold->executable environment) which I cannot complete on my own. The most "wiki" way to publish it would be to publish it incomplete and hope that someone else will complete it. Or you could take a look at it first - the short document is at https://github.com/pireddag/notes/blob/work/src/embedding-tikz-figures-short.tm and the points on which I need help are listed at the beginning.
I would postpone a section on more complex TikZ figures because they do not compile (in different ways) and it may be more complex to figure out how to fix things.
Pls. let me know.

**Comment by mgubi** [comment]
1) My impression is that the "Graph" plugin is the "modern" way to use various graphical plugins, including TiKZ. Indeed if you look at the code, the TikZ plugin just call the code in the Graph plugin. So I would just suggest to go via the Graph plugin, it is enough to add %tikz at the beginning of your example. 
2) The complex figures cannot be done (I think) within the TikZ plugin, you need the Graph plugin and the %pdflatex backend to be able to input full LaTeX files. 
3) The behaviour of S-Return seems normal. In the Help->Manual->TeXmacs as an interface, it is said that S-Return go into multi-line mode, then from that point on Return go to a new line and S-Return execute the code. Maybe you can point also to the manual page, it is useful for the Users to realise that the manual contains a lot of valuable informations (I have the impression that most of the uses never opened the manual even once...)

**Comment by pireddag** [comment]
With the graph plugin *used exclusively* I have the impression that one is losing functionality: if you want the image to be *embedded* in the text you are writing, then you have to open the graph plugin, execute, copy the output, paste where you want it; then if you want to edit the figure what do you do? I did not yet investigate it---at first sight it seems that you have to save separately the document with your work on the plugin.
To me this seems an important usability feature: is the concept of plugin "TeXmacs at the service of external programs" or "external programs at the service of TeXmacs"? These are two different applications which IMHO need to be treated differently. For this reason I started writing a blog article on the second way to use a plugin.
I do not know what Joris thinks about this but his opinion could also be crucial to keep both plugin applications active.

**Comment by mgubi** [comment]
I do not understand: you can Insert->Fold->Graph

**Comment by mgubi** [comment]
The point is that most of the plugins are just variation on a common theme and Graph provide a way to share the common code. Since you want to keep the old documents still working we must keep around the various plugins but I think we should deprecate them. Graph include the functionality of many: TiKZ, PDFLaTeX, FeynMF, etc...

**Comment by mgubi** [comment]
Actually the most general is the Latex/pdflatex backend, all the other backends in the graph plugin are implemented on top of that one.

**Comment by mgubi** [comment]
See the help page for the graph plugin

**Comment by pireddag** [comment]
I had not understood it. Let me rewrite the blog post!

**Pull request merged**
