### PR TITLE
Embedding Scheme graphics

### PR DESCRIPTION
**Pull request by pireddag**
Il modulo Scheme è src/embedGraphics.scm 
aspetto eventuali commenti

### CODE REVIEW

**Review by mgubi — COMMENTED** [review]
Can you use file names which are all lowercase and separated with '-', would be more homogeneous to the overall style of the repository. Thanks!

**Review by mgubi — CHANGES_REQUESTED** [review]
Otherwise overall it seems good to me. Also I'm trying to collect all the auxiliary files in ./resources/. subdirectories. For example you can create ./resources/embed-graphics/ and put there all the auxiliary file (e.g. scheme source, tm files which are not meant to be converted in html, figures, etc...). Do not forget to update the paths. This organisation will allow to have both tm and html pages fully functional.

**Comment by pireddag** [comment]
Changed file names and put scheme file in resources. Need to figure out how to indicate the path to the Scheme module (I know the syntax only starting from .TeXmacs, will try generalizing)

**Comment by pireddag** [comment]
I do not see how to use a Scheme module that is not in a subdirectory of .TeXmacs, I am not able to update the path names in the use-module primitive or texmacs-module Scheme function

**Comment by mgubi** [comment]
Does a relative pathname like "../resources/blah.scm" work?

**Comment by pireddag** [comment]
Tried it, but without changing the path in texmacs-module, because there .. would not refer to the same directory. Did not work. Can try again, changing the path in texmacs-module too (I saw other times that with the wrong path there TeXmacs issues error messages, but makes the functions available).

**Comment by mgubi** [comment]
What about starting from 
(path-to-buffer (current-buffer))
and building a global path? (this will not work for browsing from remove maybe)

**Comment by mgubi** [comment]
This seems to give the result
(url-append (current-buffer) "../resources/blah.scm")
use url->string to obtain a string

**Comment by pireddag** [comment]
Let me figure out how to use your suggestion. Putting .. keeps being relative to .TeXmacs/progs

**Comment by pireddag** [comment]
I tried (copying it from the source)

<use-module|(url-\<gtr\>string (url-append (current-buffer)
    "../resources/scheme-graphics-embedding/embed-graphics.scm"))

without touching the .scm file yet, TeXmacs still does not find it. Taking as good that the path name I am using is correct, what should the command look like?

**Comment by mgubi** [comment]
It is mean to be scheme code. Maybe you should directly (i.e. from scheme) load the scheme source. Use an extern markup, no?

**Comment by mgubi** [comment]
<extern|(load (url-append (current-buffer) "../resources/blah.scm"))>

**Comment by pireddag** [comment]
I see. Let me try. I have to change the concept of how to do things too, but perhaps it is ok. I do not know what is the "best" way to load Scheme commands into a TeXmacs document.

**Comment by pireddag** [comment]
It works, but on the terminal I see the error

<unnamed port>: In expression ((load #)):
<unnamed port>: Wrong type to apply: #<unspecified>

which I am not able to interpret

(no effect of the error on the functionality)

**Comment by mgubi** [comment]
Dear Giovanni, I think use-module is not necessary here. Why you just do not embed all the scheme into the document? You can put all the statements you want via an \extern tag and have more than one instruction inside a (begin ...) scheme macro

**Comment by mgubi** [comment]
load expects a string so you have to convert the url in string via url->string

**Comment by mgubi** [comment]
If you do not restart TeXmacs then the scheme will retain all the previous definitions....

**Comment by pireddag** [comment]
String is there :-)

What I would like to achieve is "no visible code in the document".

**Comment by mgubi** [comment]
You can put in the document
<extern|(begin (define A 10) (define B 20) .... )>

**Comment by mgubi** [comment]
you can put the code in the  preamble. Extern will not show up I think.

**Comment by pireddag** [comment]
Right about begin. But you will have the inconvenience of having no repl available to test your commands, if you put *everything* in the executable window.

**Comment by pireddag** [comment]
By the way it took 10 minutes to get extern ... load to work because I had to figure out first that the right keypresses to get -> and " would be available only in the preamble

**Comment by pireddag** [comment]
Long answer, because I think that this is an important issue.

I am looking for a way of making it efficient to modify the code. Id est, besides the code working, if users wants to modify it, they should have convenient tools available. I am not yet completely happy with what I found (my first version is also not good from this point of view), and I want - at least for the moment - a reasonable solution.

May be "showing the embedding of the graphics" and "showing a way to work efficiently" are two topics for two different blog posts, but I have a strong feeling that even in the first post I would like to give other users complete information: that is, not only "here you are the embedding of the graphics, we do not tell you anything else and if you want to do complex things you will find out on your own that the tools we suggested are uncomfortable".

Putting many Scheme instructions inside extern is of course providing the functionality, but it is awkward to modify the code there; I did not yet try ;-), but it looks unappealing (I am assuming you get all the error messages through the terminal). 

The most comfortable way I found in which you can compose the code, test all of the commands with error messages, *and* have it ready for running is: using an external editor to edit, having TeXmacs read the file you are editing, and using the terminal for the error messages.

Using Scheme sessions is good for testing (even extensive) but does not give you code that another TeXmacs document can immediately use: you have to copy-paste it.

By the way, loading of the file through the command you gave *is* working, but with the error I posted. The error comes up when running the fold executable, and I do not see why, as there is no load command there.

I am thinking up how much information about composing and testing the code I should put in the post, or if writing up the .tm file in a way similar to the one I would when working on it on my own, and announcing a blog post on the toolset would be enough.

**Comment by pireddag** [comment]
I think I figured out how to write it. In this post, all the code goes inside the executable window. We promise a discussion of ways to work with Scheme code, that we will write in another post.

**Comment by pireddag** [comment]
Rewritten. May be it needs refinements but looks ok to me. For the post on efficient ways to work I will ask for some help on the mailing list or the forum after I will write a first draft.

**Comment by pireddag** [comment]
The code in the last window is center-aligned :-)

**Comment by mgubi** [comment]
Corrected. Why don't you merge the two articles on scheme. They seems quite short. You can make the embedding one a subsection of the first. So you can remove all the links to the first article. This would help to avoid a chaotic first page.

**Comment by pireddag** [comment]
Let me test it on TeXmacs and see how long it feels when they are together. Maybe it works with a table of contents on top. Though short, linked articles may be good too.
What are you referring to with "chaotic first page"?
Perhaps the extremely synthetic explanation on TeXmacs' graphics? I copy it here so that we identify it:

"A synthetic discussion of TeXmacs graphics primitives and how to code them in Scheme is in the previous note (see also the manual, in Help→Manual→Creating technical pictures). Here let us just remind that TeXmacs graphics are composed by listing graphical objects, each made by the application of a graphical primitive, inside a graphics primitive.

In the code introduce a function pt that generates point primitives, (which are parametrized by two numbers, expressed as strings), and with it we generate points that we will use to build other primitives (arc, line, cline and text-at).

In turn, TeXmacs will use the primitives to represent the triangle, the half-circle and the decorations, that is the drawing that we will embed in the document."

**Comment by mgubi** [comment]
I was meaning that I would like to keep main.tm clean. Not critique of your nice work! :) Anyway, if you do not feel they go together this is fine for me. I think an article can be quite long, see e.g. wikipedia. You can provide a TOC at the beginning, even if I'm not sure that we can automate this right now.

**Comment by pireddag** [comment]
Let me think a bit more. One good thing about the current arrangement (separated files) is that it puts into evidence that embedding is possible. It took me quite a long time to find it out (despite the fact that it is in the manual).
Perhaps in the manual it is not prominent enough. Maybe a post on the abstract topic of "TeXmacs at the service of other programs _versus_ other programs at the service of TeXmacs" could be useful.

**Comment by pireddag** [comment]
By the way I am thinking of a small Scheme function to flatten lists conditionally (it stops flattening when it meets the symbol "with" or one of the graphical primitives). In this way I would be able to do combine graphics in a modular way, nesting them arbitrarily. But I need some time.

**Comment by mgubi** [comment]
You may want to look at https://elephly.net/posts/2018-09-01-guile-picture-language.html
for some ideas on how to improve the graphical support in scheme. In general I think there is a lot of research on the functional description of graphics and this could be inspiring.

**Comment by pireddag** [comment]
> I was meaning that I would like to keep main.tm clean. 

There probably some further organization will help; as the blog grows either with short or with long articles. Maybe adding pages for sub-directories? Other possibilities are a system of tags and/or a search field and/or a list of links in a side pane.

**Comment by mgubi** [comment]
I think we will transition slowly to a more ramified organisation with subtrees. I wanted to keep the "static" look as far as possible. Like a traditional publication. On the side however we could indeed give the possibility to search by tag or to navigate the site via alternative views (static or dynamic). But for the moment I would like to keep simple.

**Pull request merged**
