### PR TITLE
Refinements to the post on tikz embedding

### PR DESCRIPTION
**Pull request by pireddag**

### CODE REVIEW

**Review by mgubi — APPROVED** [review]

**Comment by pireddag** [comment]
The .tm file is now in the repository but there is no file at https://texmacs.github.io/notes/embedding-tikz-figures-short.html

**Comment by mgubi** [comment]
I have a problem to generate the images. Can you provide the .html and the related images?

**Comment by pireddag** [comment]
I also am not able to generate the images when converting to html. Maybe I can generate them from TeXmacs - I hope their size is right in this case. Will try and in case submit a PR

**Comment by mgubi** [comment]
I think there is a problem with .ps and .pdf  image files in the HTML conversion.

**Comment by pireddag** [comment]
Saving the images of the filled rectangles from TeXmacs generates .ps files (only format I have seen an option for) that crash Okular.

**Comment by mgubi** [comment]
I think I managed to produce the images (not really sure how...). They are online.

**Pull request merged**
