### PR TITLE
Post on macro editor and formatting changes to README.md

### PR DESCRIPTION
**Pull request by pireddag**
Updated after revising the first version of the blog post on the Macro editor

### CODE REVIEW

**Comment by da-liii** [comment]
The macro editor is not very user friendly. I'm really confused sometimes. I will review this PR as soon as possible.

**Review by da-liii — APPROVED** [review]

**Comment by da-liii** [comment]
An awesome post! Let me fix the [bug](https://savannah.gnu.org/bugs/?60015) you mentioned in this note as soon as possible. Any other updates? Is it ready to be merged?

**Comment by pireddag** [comment]
Hi, yes, from my point of view yes. with this small note: I hope that calling the "green" variables (that is, the variables typeset in green font) "Environment variables" is correct. If not, I can change that. Otherwise it is ready.

**Comment by da-liii** [comment]
We might talk about how to make a user-defined todo with a nice focus menu/toolbar in the next post of the macro series. eg. a focus toolbar with a todo/done switcher.

**Comment by pireddag** [comment]
> We might talk about how to make a user-defined todo with a nice focus menu/toolbar in the next post of the macro series. eg. a focus toolbar with a todo/done switcher.

It could be: if understood "show users how they could make it", it could be a useful post. Said this, I think we need to systematically cover the "easy to intermediate" topics

**Comment by da-liii** [comment]
> with this small note: I hope that calling the "green" variables (that is, the variables typeset in green font) "Environment variables" is correct. If not, I can change that. Otherwise it is ready.

Environment variables reminds me of the variables listed by the command line `env`. You've put a link to https://www.texmacs.org/tmweb/manual/webman-env.en.html . 

I think it is correct.

**Comment by pireddag** [comment]
> Environment variables reminds me of the variables listed by the command line env. You've put a link to https://www.texmacs.org/tmweb/manual/webman-env.en.html .

>I think it is correct.

Ok, then from my point of view it is ready for merging.

**Comment by da-liii** [comment]
> It could be: if understood "show users how they could make it", it could be a useful post. Said this, I think we need to systematically cover the "easy to intermediate" topics.

Topic on macro editors is already an intermediate topic. I think it's fine to go further to show the power of GNU TeXmacs. Many cool functionalities of GNU TeXmacs need to be revealed. They exist, but most of us does not know about them.

**Comment by pireddag** [comment]
> They exist, but most of us does not know about it.

We can try. As immediately next topic, I would like to complete the series on the graphical language by showing how to use external Scheme files. Immediately after that, we could work on the post on todo/done notes (I have to learn something to do that, and I hope I am going to learn it while preparing that post).

**Comment by mgubi** [comment]
Great work @pireddag ! Could you add an abstract? (look at some other file). Also  there is a script to update the page with all the articles and also the atom feed. Can you run it when you add a new article. (I should automate this but still could not find the time...)

**Comment by pireddag** [comment]
> Could you add an abstract?

I'll do it. The abstract formatting in the notes style does not work well, by the way: the text does not wrap around.
I'll also run the script.

**Comment by pireddag** [comment]
> The abstract formatting in the notes style does not work well, by the way

I figured it out: it is notes-abstract.
I'll add a description of this in the README.md file

**Pull request merged**
