### PR TITLE
Small fix to scheme tutorial

### PR DESCRIPTION
**Pull request by mgubi**

### CODE REVIEW

**Comment by pireddag** [comment]
The last Scheme drawing (the complete one) did not get converted.

**Comment by mgubi** [comment]
Corrected.

**Comment by pireddag** [comment]
Almost there :-) : now the last image is there twice ;-)

**Comment by mgubi** [comment]
To me looks fine. What do you mean?

**Comment by pireddag** [comment]
The figure after the last Scheme code (the complete one) should be the triangle inscribed in the semicircle; right now it is a copy of the last figure that I made with the graphical editor)

**Comment by mgubi** [comment]
This is not what I see. After the last scheme code I see a triangle in the semicircle with the TeXmacs text and A,B,C points and some white space below before the last paragraph, then the image with a panorama of graphics objects.

**Comment by pireddag** [comment]
Now I see it too. It was different when I wrote the previous comment.

**Comment by pireddag** [comment]
Said this, I will read it again tomorrow, and correct/refine it (probably some small corrections/refinements are necessary/possible).

**Comment by mgubi** [comment]
It takes some time for the server to propagate the changes.

**Comment by pireddag** [comment]
Ok: the "panorama" figure appearing twice looked like it had to be corrected.

**Comment by pireddag** [comment]
BTW, if you find the way and the time, an addition to the css for highlighting Scheme code would be nice.

**Comment by mgubi** [comment]
Yes, it is on my radar. I have to understand what is happening there. A priori the colouring should go thru.

**Pull request merged**
