### PR TITLE
New Note: Customize syntax color

### PR DESCRIPTION
**Pull request by da-liii**

### CODE REVIEW

**Review by mgubi — CHANGES_REQUESTED** [review]
Can you provide a title (with \chapter) and maybe a small abstract or introduction to summarise the aim of the article? you can use the \notes-abstract tag if you want.

**Comment by da-liii** [comment]
Rebase on master, please review again.

**Comment by da-liii** [comment]
I changed settings in https://github.com/texmacs/notes/settings .

Do you agree `Squash and merge` is better? If not, you may reset the settings.

**Comment by mgubi** [comment]
> I changed settings in https://github.com/texmacs/notes/settings .
> 
> Do you agree `Squash and merge` is better? If not, you may reset the settings.

I think   `Squash and merge` is indeed better. I'm not much used to manage PR. I'm learning.

**Review by mgubi — APPROVED** [review]

**Comment by da-liii** [comment]
I remember there is a thread in texmacs-users discussing about using code snippet but does not want to keep the color. But I can't find it right now. This note is for that thread.

**Comment by pireddag** [comment]
I propose to change (slightly) the following sentence or to reorganize the text on this concept a bit, to make it more prominent:
"Preferences are stored when we set it. For GNU TeXmacs v1.99.15, a re-render trigger (eg. Restart) is required for your changes to take effect."

From this sentence I understand that setting the preference through the Scheme session will change it for all documents, both in the current TeXmacs session and in future sessions. Is that in this way? Besides, perhaps it can be stated just before the Scheme session, that is next to the sentence "It is controlled by the following preference:"

For example (the statement or some terms may be wrong, but it is to explain what I have in mind):

It is controlled by the  "syntax:cpp:preprocessor_directive" preference; TeXmacs preferences can be set globally through a Scheme session:

and then you start the Scheme session with the (get-preference "syntax:cpp:preprocessor_directive") expression and so on.

Maybe doing this will help clarifying the concept that one can use a Scheme session to change preferences, and then he can use the new preferences in other documents where there is no open Scheme session, which IMO is not an evident thing for users.
Even, one could make a post about the concept itself (use Scheme sessions to control the behaviour of the program, get the desired behaviour in all documents), which may or may not be clear to each person that reads the blog (for example, it is not clear to me, and I have had a few years of time to use TeXmacs).

Said this, if there is some documentation on this preference in the manual, one could point to it, if there is not, maybe state that this is "yet undocumented".

All IMO of course.

G.

**Comment by da-liii** [comment]
Thanks for your advice. Besides, feel free if there are any grammar errors in my notes. I'm not well trained in English Writing. Sometimes, I may write in chi-english style.

**Comment by pireddag** [comment]
As a reader, I know what I would like to read, and since I am writing here I can ask the writers :-)

**Pull request merged**
